FROM openjdk:21-jdk-slim

RUN apt-get update && \
    apt-get install -y jq openssl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY app.jar /app/app.jar
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
